import type { FileNode } from '../types';
import { createFileSystem, type MachineFileSystemConfig } from '../fileSystemFactory';

const gatewayGuestHome: Readonly<Record<string, FileNode>> = {
  '.bash_history': {
    name: '.bash_history',
    type: 'file',
    owner: 'guest',
    permissions: { read: ['root', 'user', 'guest'], write: ['root', 'guest'], execute: ['root'] },
    content: `ls
pwd
cat /etc/passwd
ls /var/log
`,
  },
};

const gatewayConfig: MachineFileSystemConfig = {
  users: [
    {
      username: 'admin',
      passwordHash: 'dab569cb96513965ca00379d69b2f40c',
      userType: 'root',
      uid: 0,
    }, // n3tgu4rd!
    {
      username: 'guest',
      passwordHash: 'dbf0171774108c80c94819b1ce0dbd9b',
      userType: 'guest',
      uid: 1001,
      homeContent: gatewayGuestHome,
    }, // guest2024
  ],
  etcExtraContent: {
    hostname: {
      name: 'hostname',
      type: 'file',
      owner: 'root',
      permissions: { read: ['root', 'user', 'guest'], write: ['root'], execute: ['root'] },
      content: 'gateway\n',
    },
    hosts: {
      name: 'hosts',
      type: 'file',
      owner: 'root',
      permissions: { read: ['root', 'user', 'guest'], write: ['root'], execute: ['root'] },
      content: `127.0.0.1       localhost
192.168.1.1     gateway gateway.local
192.168.1.50    fileserver.local
192.168.1.75    webserver.local
192.168.1.100   jshack-dev
`,
    },
    'iptables.rules': {
      name: 'iptables.rules',
      type: 'file',
      owner: 'root',
      permissions: { read: ['root', 'user', 'guest'], write: ['root'], execute: ['root'] },
      content: `# Generated by iptables-save v1.8.7
*filter
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -i lo -j ACCEPT
-A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT
-A INPUT -p tcp --dport 22 -j ACCEPT
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT
-A INPUT -p icmp --icmp-type echo-request -j ACCEPT
-A INPUT -j DROP
COMMIT
`,
    },
  },
  rootContent: {
    // FLAG 5: Root flag on gateway
    'flag.txt': {
      name: 'flag.txt',
      type: 'file',
      owner: 'root',
      permissions: { read: ['root'], write: ['root'], execute: ['root'] },
      content: `FLAG{gateway_breach}

The admin panel at /var/www/html/admin.html contains
network configuration details. Check it out.

Also noticed unusual FTP traffic to 192.168.1.50.
Default FTP credentials are often "anonymous".
`,
    },
    // HINT: Network credentials for next machines
    '.network_config': {
      name: '.network_config',
      type: 'file',
      owner: 'root',
      permissions: { read: ['root'], write: ['root'], execute: ['root'] },
      content: `Network Configuration Notes
============================
Gateway: admin / [see auth logs]
Fileserver FTP: guest/anonymous, ftpuser/tr4nsf3r
Webserver: guest/w3lcome, www-data/[ask DevOps]
Darknet: RESTRICTED — do not connect
`,
    },
  },
  // FLAG 4 & 6: Web content + HINT: auth.log with admin password
  extraDirectories: {
    var: {
      name: 'var',
      type: 'directory',
      owner: 'root',
      permissions: {
        read: ['root', 'user', 'guest'],
        write: ['root'],
        execute: ['root', 'user', 'guest'],
      },
      children: {
        log: {
          name: 'log',
          type: 'directory',
          owner: 'root',
          permissions: {
            read: ['root', 'user', 'guest'],
            write: ['root'],
            execute: ['root', 'user', 'guest'],
          },
          children: {
            'auth.log': {
              name: 'auth.log',
              type: 'file',
              owner: 'root',
              permissions: {
                read: ['root', 'user', 'guest'],
                write: ['root'],
                execute: ['root'],
              },
              content: `Mar 10 08:15:22 gateway sshd[1234]: Failed password for admin from 192.168.1.100
Mar 10 08:15:25 gateway sshd[1234]: Failed password for admin from 192.168.1.100
Mar 10 09:30:01 gateway sshd[1235]: Accepted password for admin from 10.0.0.5
Mar 11 14:22:10 gateway sshd[1240]: Failed password for root from 203.0.113.42
Mar 11 14:22:15 gateway sshd[1240]: Failed password for root from 203.0.113.42
Mar 12 03:00:00 gateway sshd[1250]: pam_audit: admin authenticated with password 'n3tgu4rd!'
Mar 12 03:00:01 gateway sshd[1250]: session opened for admin
Mar 13 11:00:00 gateway sshd[1260]: Connection from 192.168.1.50 port 22
`,
            },
            'firewall.log': {
              name: 'firewall.log',
              type: 'file',
              owner: 'root',
              permissions: {
                read: ['root', 'user', 'guest'],
                write: ['root'],
                execute: ['root'],
              },
              content: `Mar 10 00:05:12 gateway kernel: DROP IN=eth0 SRC=45.33.32.156 DST=192.168.1.1 PROTO=TCP DPT=23
Mar 10 01:22:45 gateway kernel: DROP IN=eth0 SRC=185.220.101.34 DST=192.168.1.1 PROTO=TCP DPT=3389
Mar 10 03:14:00 gateway kernel: DROP IN=eth0 SRC=91.240.118.50 DST=192.168.1.1 PROTO=TCP DPT=445
Mar 11 06:30:22 gateway kernel: DROP IN=eth0 SRC=203.0.113.42 DST=192.168.1.1 PROTO=TCP DPT=8080
Mar 11 14:22:08 gateway kernel: DROP IN=eth0 SRC=203.0.113.42 DST=192.168.1.1 PROTO=TCP DPT=4444
Mar 12 09:00:00 gateway kernel: ACCEPT IN=eth1 SRC=192.168.1.75 DST=192.168.1.1 PROTO=TCP DPT=80
`,
            },
          },
        },
        www: {
          name: 'www',
          type: 'directory',
          owner: 'root',
          permissions: {
            read: ['root', 'user', 'guest'],
            write: ['root'],
            execute: ['root', 'user', 'guest'],
          },
          children: {
            html: {
              name: 'html',
              type: 'directory',
              owner: 'root',
              permissions: {
                read: ['root', 'user', 'guest'],
                write: ['root'],
                execute: ['root', 'user', 'guest'],
              },
              children: {
                'index.html': {
                  name: 'index.html',
                  type: 'file',
                  owner: 'root',
                  permissions: {
                    read: ['root', 'user', 'guest'],
                    write: ['root'],
                    execute: ['root'],
                  },
                  content: `<!DOCTYPE html>
<html>
<head><title>NetGuard Router</title></head>
<body>
<h1>NetGuard Router v3.2.1</h1>
<p>Administration portal</p>
<p>Authorized personnel only.</p>
<!-- FLAG{network_explorer} -->
<!-- Admin panel: /admin.html (restricted) -->
<!-- Default credentials may still be in the system logs -->
</body>
</html>
`,
                },
                'admin.html': {
                  name: 'admin.html',
                  type: 'file',
                  owner: 'root',
                  permissions: { read: ['root'], write: ['root'], execute: ['root'] },
                  content: `<!DOCTYPE html>
<html>
<head><title>NetGuard Admin Panel</title></head>
<body>
<h1>NetGuard Admin Panel</h1>
<h2>Network Configuration</h2>
<table>
  <tr><td>Gateway</td><td>192.168.1.1</td></tr>
  <tr><td>File Server</td><td>192.168.1.50</td></tr>
  <tr><td>Web Server</td><td>192.168.1.75</td></tr>
  <tr><td>External</td><td>203.0.113.42 (darknet.ctf)</td></tr>
</table>
<!-- FLAG{admin_panel_exposed} -->
<!-- Maintenance note: webserver guest account uses default password -->
</body>
</html>
`,
                },
                'robots.txt': {
                  name: 'robots.txt',
                  type: 'file',
                  owner: 'root',
                  permissions: {
                    read: ['root', 'user', 'guest'],
                    write: ['root'],
                    execute: ['root'],
                  },
                  content: `User-agent: *
Disallow: /admin.html
Disallow: /backup/
Disallow: /config/
`,
                },
                css: {
                  name: 'css',
                  type: 'directory',
                  owner: 'root',
                  permissions: {
                    read: ['root', 'user', 'guest'],
                    write: ['root'],
                    execute: ['root', 'user', 'guest'],
                  },
                  children: {
                    'style.css': {
                      name: 'style.css',
                      type: 'file',
                      owner: 'root',
                      permissions: {
                        read: ['root', 'user', 'guest'],
                        write: ['root'],
                        execute: ['root'],
                      },
                      content: `/* NetGuard Router UI */
body { font-family: Arial, sans-serif; margin: 0; padding: 20px; background: #f5f5f5; }
h1 { color: #2c3e50; border-bottom: 2px solid #3498db; padding-bottom: 10px; }
table { border-collapse: collapse; width: 100%; }
td { padding: 8px; border: 1px solid #ddd; }
.status-ok { color: #27ae60; }
.status-warn { color: #e67e22; }
`,
                    },
                  },
                },
              },
            },
          },
        },
      },
    },
  },
};

export const gateway: FileNode = createFileSystem(gatewayConfig);
