import { writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { localhost } from '../src/filesystem/machines/localhost';
import { gateway } from '../src/filesystem/machines/gateway';
import { fileserver } from '../src/filesystem/machines/fileserver';
import { webserver } from '../src/filesystem/machines/webserver';
import { darknet } from '../src/filesystem/machines/darknet';
import { shadow } from '../src/filesystem/machines/shadow';
import { voidFs } from '../src/filesystem/machines/void';
import { abyss } from '../src/filesystem/machines/abyss';
import { encodeFileSystem } from '../src/utils/contentCodec';

const __dirname = dirname(fileURLToPath(import.meta.url));

const machines = [
  ['localhost', localhost],
  ['gateway', gateway],
  ['fileserver', fileserver],
  ['webserver', webserver],
  ['darknet', darknet],
  ['shadow', shadow],
  ['voidFs', voidFs],
  ['abyss', abyss],
] as const;

const encodedEntries = machines.map(
  ([name, tree]) => [name, JSON.stringify(encodeFileSystem(tree))] as const,
);

const lines = [
  '// Auto-generated by scripts/encode-filesystems.ts — do not edit',
  "import type { FileNode } from '../types';",
  "import { decodeFileSystem } from '../../utils/contentCodec';",
  '',
  'const p = (json: string): FileNode => decodeFileSystem(JSON.parse(json));',
  '',
  ...encodedEntries.map(
    ([name, json]) => `export const ${name}: FileNode = p(${JSON.stringify(json)});`,
  ),
  '',
];

const outPath = resolve(__dirname, '../src/filesystem/machines/__encoded.ts');
writeFileSync(outPath, lines.join('\n'), 'utf-8');

console.log(`Wrote ${outPath}`);
